name: bad
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.5.2
  - pip=23.2.1
  - python=3.8.17
  - pyyaml=6.0.1
  - requests=2.31.0
  - setuptools=68.2.2
  - yaml=0.2.5
  - pip:
      - accelerate==0.24.1
      - diffusers==0.23.1
      - einops==0.3.0
      - flask==3.0.0
      - flask-cors==4.0.0
      - gradio==3.48.0
      - gradio-client==0.6.1
      - imageio==2.9.0
      - imageio-ffmpeg==0.4.2
      - matplotlib==3.7.3
      - multiprocess==0.70.15
      - omegaconf==2.3.0
      - opencv-contrib-python==4.3.0.36
      - opencv-python==4.8.1.78
      - opencv-python-headless==4.8.1.78
      - pillow==9.4.0
      - pytorch-lightning==1.5.0
      - safetensors==0.4.0
      - scikit-image==0.20.0
      - scikit-learn==1.3.1
      - scipy==1.9.1
      - threadpoolctl==3.2.0
      - tokenizers==0.14.1
      - torch==2.1.1
      - torchmetrics==0.6.0
      - torchvision==0.16.1
      - tqdm==4.66.1
      - transformers==4.34.1
      - watchdog==3.0.0
      - open-clip-torch==2.0.2